"""Socle — les dix entités de la section 5.1.

Première révision. Le schéma ne porte AUCUNE colonne de comptage :
`nb_generations` et `nb_tentatives` se calculent depuis le journal
(EX-GEN-07, EX-IA-21). `chronique.lieu` contient un code stable et non
un libellé (EX-IA-28, EX-IA-42).

La table `participation` du banc d'essai, si elle existe dans une base
déjà déployée, est laissée intacte : toute suppression est douce
(EX-GEN-03) et se décide à la main.

Révision : 0001_socle
Précédente : 
Créée le : 2026-08-19 11:21:07.271102+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001_socle'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etat_soiree',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phase', sa.String(length=20), nullable=False),
    sa.Column('fermeture_prevue_le', sa.DateTime(), nullable=True),
    sa.Column('modifie_le', sa.DateTime(), nullable=False),
    sa.CheckConstraint("phase IN ('preparation','ouvert','dernier_appel','lecture_seule','ferme')", name='ck_etat_soiree_phase'),
    sa.CheckConstraint('id = 1', name='ck_etat_soiree_unique'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journal',
    sa.Column('horodatage', sa.DateTime(), nullable=False),
    sa.Column('acteur_personne_uuid', sa.String(length=36), nullable=True),
    sa.Column('agit_pour_le_compte_de', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('objet_type', sa.String(length=30), nullable=True),
    sa.Column('objet_uuid', sa.String(length=36), nullable=True),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('journal', schema=None) as batch_op:
        batch_op.create_index('ix_journal_horodatage', ['horodatage'], unique=False)
        batch_op.create_index('ix_journal_objet_action', ['objet_uuid', 'action'], unique=False)

    op.create_table('sauvegarde',
    sa.Column('horodatage', sa.DateTime(), nullable=False),
    sa.Column('cible', sa.String(length=40), nullable=False),
    sa.Column('nb_objets', sa.Integer(), nullable=False),
    sa.Column('octets', sa.Integer(), nullable=False),
    sa.Column('succes', sa.Boolean(), nullable=False),
    sa.Column('erreur', sa.Text(), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('sauvegarde', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sauvegarde_horodatage'), ['horodatage'], unique=False)

    op.create_table('table_groupe',
    sa.Column('nom', sa.String(length=80), nullable=False),
    sa.Column('ordre', sa.Integer(), nullable=False),
    sa.Column('code_responsable', sa.String(length=40), nullable=True),
    sa.Column('est_test', sa.Boolean(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('tache',
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('objet_uuid', sa.String(length=36), nullable=False),
    sa.Column('priorite', sa.Integer(), nullable=False),
    sa.Column('etat', sa.String(length=20), nullable=False),
    sa.Column('tentatives', sa.Integer(), nullable=False),
    sa.Column('reprendre_apres', sa.DateTime(), nullable=True),
    sa.Column('derniere_erreur', sa.Text(), nullable=True),
    sa.Column('creee_le', sa.DateTime(), nullable=False),
    sa.Column('demarree_le', sa.DateTime(), nullable=True),
    sa.Column('terminee_le', sa.DateTime(), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.CheckConstraint("etat IN ('en_attente','en_cours','terminee','echouee')", name='ck_tache_etat'),
    sa.CheckConstraint("type IN ('generation_chronique','conversion_image','copie_stockage_objet')", name='ck_tache_type'),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('tache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tache_objet_uuid'), ['objet_uuid'], unique=False)
        batch_op.create_index('ix_tache_service', ['etat', 'priorite', 'creee_le'], unique=False)
        batch_op.create_index('ux_tache_generation_en_cours', ['objet_uuid'], unique=True, sqlite_where=sa.text("type = 'generation_chronique' AND etat IN ('en_attente', 'en_cours')"))

    op.create_table('personne',
    sa.Column('table_uuid', sa.String(length=36), nullable=True),
    sa.Column('prenom', sa.String(length=80), nullable=False),
    sa.Column('nom', sa.String(length=80), nullable=False),
    sa.Column('genre', sa.String(length=10), nullable=True),
    sa.Column('identifiant_import', sa.String(length=80), nullable=True),
    sa.Column('est_responsable', sa.Boolean(), nullable=False),
    sa.Column('est_marie', sa.Boolean(), nullable=False),
    sa.Column('est_test', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.CheckConstraint("genre IS NULL OR genre IN ('masculin', 'feminin')", name='ck_personne_genre'),
    sa.CheckConstraint("source IN ('import', 'saisie_libre', 'kiosque')", name='ck_personne_source'),
    sa.ForeignKeyConstraint(['table_uuid'], ['table_groupe.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('personne', schema=None) as batch_op:
        batch_op.create_index('ix_personne_nom', ['nom', 'prenom'], unique=False)
        batch_op.create_index('ux_personne_identifiant_import', ['identifiant_import'], unique=True, sqlite_where=sa.text('identifiant_import IS NOT NULL'))

    op.create_table('appareil',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('personne_uuid', sa.String(length=36), nullable=False),
    sa.Column('premiere_vue', sa.DateTime(), nullable=False),
    sa.Column('derniere_vue', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['personne_uuid'], ['personne.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('appareil', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appareil_personne_uuid'), ['personne_uuid'], unique=False)

    op.create_table('chronique',
    sa.Column('personne_uuid', sa.String(length=36), nullable=False),
    sa.Column('appareil_uuid', sa.String(length=36), nullable=True),
    sa.Column('est_test', sa.Boolean(), nullable=False),
    sa.Column('lieu', sa.String(length=20), nullable=False),
    sa.Column('reponses_json', sa.Text(), nullable=False),
    sa.Column('etage', sa.Integer(), nullable=False),
    sa.Column('nom_fictif', sa.String(length=120), nullable=True),
    sa.Column('peuple', sa.String(length=40), nullable=True),
    sa.Column('portrait', sa.Text(), nullable=True),
    sa.Column('indice', sa.Text(), nullable=True),
    sa.Column('fuites_noms_json', sa.Text(), nullable=True),
    sa.Column('modele', sa.String(length=60), nullable=True),
    sa.Column('duree_s', sa.Float(), nullable=True),
    sa.Column('jetons_entree', sa.Integer(), nullable=True),
    sa.Column('jetons_sortie', sa.Integer(), nullable=True),
    sa.Column('etat', sa.String(length=20), nullable=False),
    sa.Column('derniere_erreur', sa.Text(), nullable=True),
    sa.Column('validee', sa.Boolean(), nullable=False),
    sa.Column('supprimee', sa.Boolean(), nullable=False),
    sa.Column('creee_le', sa.DateTime(), nullable=False),
    sa.Column('modifiee_le', sa.DateTime(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.CheckConstraint("etat IN ('brouillon','en_attente','en_cours','prete','echouee')", name='ck_chronique_etat'),
    sa.CheckConstraint('etage IN (1, 2)', name='ck_chronique_etage'),
    sa.ForeignKeyConstraint(['personne_uuid'], ['personne.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('chronique', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chronique_etat'), ['etat'], unique=False)
        batch_op.create_index(batch_op.f('ix_chronique_lieu'), ['lieu'], unique=False)
        batch_op.create_index(batch_op.f('ix_chronique_personne_uuid'), ['personne_uuid'], unique=False)
        batch_op.create_index('ux_chronique_personne', ['personne_uuid'], unique=True, sqlite_where=sa.text('supprimee = 0'))

    op.create_table('photo',
    sa.Column('personne_uuid', sa.String(length=36), nullable=False),
    sa.Column('table_uuid', sa.String(length=36), nullable=True),
    sa.Column('portee', sa.String(length=20), nullable=False),
    sa.Column('est_test', sa.Boolean(), nullable=False),
    sa.Column('chemin_original', sa.String(length=400), nullable=False),
    sa.Column('chemin_web', sa.String(length=400), nullable=True),
    sa.Column('chemin_vignette', sa.String(length=400), nullable=True),
    sa.Column('etat', sa.String(length=20), nullable=False),
    sa.Column('supprimee', sa.Boolean(), nullable=False),
    sa.Column('supprimee_le', sa.DateTime(), nullable=True),
    sa.Column('creee_le', sa.DateTime(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.CheckConstraint("etat IN ('traitement', 'prete', 'echouee')", name='ck_photo_etat'),
    sa.CheckConstraint("portee IN ('personnelle', 'table')", name='ck_photo_portee'),
    sa.ForeignKeyConstraint(['personne_uuid'], ['personne.uuid'], ),
    sa.ForeignKeyConstraint(['table_uuid'], ['table_groupe.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_photo_personne_uuid'), ['personne_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_photo_table_uuid'), ['table_uuid'], unique=False)

    op.create_table('reclamation',
    sa.Column('personne_uuid', sa.String(length=36), nullable=False),
    sa.Column('objet_type', sa.String(length=30), nullable=False),
    sa.Column('objet_uuid', sa.String(length=36), nullable=False),
    sa.Column('texte', sa.Text(), nullable=False),
    sa.Column('traitee', sa.Boolean(), nullable=False),
    sa.Column('creee_le', sa.DateTime(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['personne_uuid'], ['personne.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('reclamation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reclamation_objet_uuid'), ['objet_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_reclamation_personne_uuid'), ['personne_uuid'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reclamation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reclamation_personne_uuid'))
        batch_op.drop_index(batch_op.f('ix_reclamation_objet_uuid'))

    op.drop_table('reclamation')
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_photo_table_uuid'))
        batch_op.drop_index(batch_op.f('ix_photo_personne_uuid'))

    op.drop_table('photo')
    with op.batch_alter_table('chronique', schema=None) as batch_op:
        batch_op.drop_index('ux_chronique_personne', sqlite_where=sa.text('supprimee = 0'))
        batch_op.drop_index(batch_op.f('ix_chronique_personne_uuid'))
        batch_op.drop_index(batch_op.f('ix_chronique_lieu'))
        batch_op.drop_index(batch_op.f('ix_chronique_etat'))

    op.drop_table('chronique')
    with op.batch_alter_table('appareil', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appareil_personne_uuid'))

    op.drop_table('appareil')
    with op.batch_alter_table('personne', schema=None) as batch_op:
        batch_op.drop_index('ux_personne_identifiant_import', sqlite_where=sa.text('identifiant_import IS NOT NULL'))
        batch_op.drop_index('ix_personne_nom')

    op.drop_table('personne')
    with op.batch_alter_table('tache', schema=None) as batch_op:
        batch_op.drop_index('ux_tache_generation_en_cours', sqlite_where=sa.text("type = 'generation_chronique' AND etat IN ('en_attente', 'en_cours')"))
        batch_op.drop_index('ix_tache_service')
        batch_op.drop_index(batch_op.f('ix_tache_objet_uuid'))

    op.drop_table('tache')
    op.drop_table('table_groupe')
    with op.batch_alter_table('sauvegarde', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sauvegarde_horodatage'))

    op.drop_table('sauvegarde')
    with op.batch_alter_table('journal', schema=None) as batch_op:
        batch_op.drop_index('ix_journal_objet_action')
        batch_op.drop_index('ix_journal_horodatage')

    op.drop_table('journal')
    op.drop_table('etat_soiree')
    # ### end Alembic commands ###
